package com.eventour.eventour.model;

public enum CategoriaEvento {
    DEPORTESYAVENTURA,
    GASTRONOMIAYVINO,
    FERIASYEXPOSICIONES,
    MUSICAYESPECTACULOS,
    ARTEYCULTURA,
    CHARLASYEVENTOSEMPRESARIALES,    
}
